# Generated by Django 6.0.1 on 2026-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "follow"),
                            (1, "post_like"),
                            (2, "comment"),
                            (3, "comment_like"),
                        ]
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
