# Generated by Django 5.2.10 on 2026-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.IntegerField(choices=[(0, 'account'), (1, 'comment'), (2, 'post')])),
                ('reason', models.CharField(max_length=1000)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
